sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: zxb
    password: 1234
  redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
  alioss:
    access-key-id: LTAI5tNUN8Pck2rqpaokXXLm
    access-key-secret: FitZeg0PPWN43EpmWZtTEWtoULZtDU
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: web-mytalis9669
  wechat:
    appid: wxd0644ce770e34511
    secret: 102b23ede768af6853077c5ba717a831